name: Gildorym
authors: [Lucariatias, godpuppet, melodichand, Hohahihehu]
version: 2.1.8
main: com.gildorymrp.gildorym.Gildorym
commands:
    newcharacter:
        usage: /<command>
        description: Resets all character data
    setname:
        usage: /cmd <name> <name> <name> <name> <name>
        description: Sets your name
    setnameother:
        usage: /cmd [user] <name> <name> <name> <name> <name>
    rollinfo:
        usage: /<command>
        description: Shows your roll info
    roll:
        usage: /<command> [roll]
        description: Rolls, broadcasting the result to players within 24 blocks
    addlore:
        usage: /<command> [loretext]
        description: Adds additional lore text to the item in hand.
    removelore:
        usage: /<command>
        description: Removes lore text from the item in hand.
    renameitem:
        usage: /<command> [name]
        description: Changes the display name of the item in hand.
    setlore:
        usage: /<command> [loretext]
        description: Sets the lore text of the item in hand.
    signitem:
        usage: /<command>
        description: Signs the user's name onto the item in hand.
    radiusemote:
        description: Sends an emote to a certain radius. Use && for colours.
        usage: /<command> [radius] [message]
permissions:
    gildorym.createboatsigns:
        description: Allows the user to creat boat signs.
        default: op
    gildorym.radiusemote:
        description: Allows using of radius emotes.
        default: op
    gildorym.falldamagealert:
        description: Allows you to be notified of fall distances
        default: op
    gildorym.setname:
        description: Allows you to set your name.
        default: op
    gildorym.setname.title:
        description: Allows you to set your title.
        default: op
    gildorym.setname.other:
        description: Allows you to set someone elses name.
        default: op
    gildorym.setname.*:
        description: Allows you to use all setname commands
        default: op
        children:
            gildorym.setname.title: true
            gildorym.setname.other: true
    gildorym.mec.addlore:
        description: Allows you to add lore to items
        default: op
    gildorym.mec.removelore:
        description: Allows you to remove lore from items
        default: op
    gildorym.mec.renameitem:
        description: Allows you to rename items
        default: op
    gildorym.mec.setlore:
        description: Allows you to set lore on items
        default: op
    gildorym.mec.signitem:
        description: Allows you to sign items
        default: op
    gildorym.mec.*:
        description: Allows you to use all mec commands
        default: op
        children:
            gildorym.mec.addlore: true
            gildorym.mec.removelore: true
            gildorym.mec.renameitem: true
            gildorym.mec.setlore: true
            gildorym.mec.signitem: true
