name: Gildorym
authors: [Lucariatias, godpuppet, melodichand]
version: 2.1.8
main: com.gildorymrp.gildorym.Gildorym
commands:
    newcharacter:
        usage: /<command>
        description: Resets all character data
    setname:
        usage: /cmd [name] <name> <name> <name> <name>
        description: Sets your surname
    rollinfo:
        usage: /<command>
        description: Shows your roll info
    roll:
        usage: /<command> [roll]
        description: Rolls, broadcasting the result to players within 32 blocks
